### ISSUE TITLE
Warning on world load after game update

### ISSUE THREAD

**Issue by Pulverizer** [MSchmoecker/FenceSnap#1] opened 2024-04-10 15:04 UTC
Game updated today and now mod prints this warning in the logs on world load:

```
[Warning: FenceSnap] Prefab wooden_fence_1 not found. Cannot fix piece
[Warning: FenceSnap] Prefab wooden_fence_1_gate not found. Cannot add snappoints
[Warning: FenceSnap] Prefab wooden_fence_2 not found. Cannot add snappoints
[Warning: FenceSnap] Prefab wooden_fence_2_gate not found. Cannot add snappoints
[Warning: FenceSnap] Prefab refined_sharpstakes not found. Cannot add snappoints
```

**Comment by MSchmoecker** [comment] 2024-04-11 19:54
Please post your full log file from BepInEx/LogOutput.log, I cannot reproduce those warning with only FenceSnap installed (Valheim 0.217.46)

**Comment by MSchmoecker** [comment] 2024-05-20 08:11
Closing due to lack of information, feel free to reopen if it can be reproduced

**Closed as completed by MSchmoecker** 2024-05-20 08:11 UTC
